### ISSUE TITLE
Suitable CLI Library

### ISSUE THREAD

**Issue by 5310** [Hashfyre/pyzure-cli#5]
Even though I recommend [Cliff](http://docs.openstack.org/developer/cliff/index.html) myself, I found out how unpythonic it is, and more importantly, how it doesn't really support multi-level commands out of the box for more than one additional level.

The only way would be to either manually handle our second-level onward arguments, or create a custom [`Command`](http://docs.openstack.org/developer/cliff/classes.html#command) class that is also an [`App`](http://docs.openstack.org/developer/cliff/classes.html#app), but the problem is [`App.run()`](http://docs.openstack.org/developer/cliff/classes.html#cliff.app.App.run) takes `argv`, but [`Command.run()`](http://docs.openstack.org/developer/cliff/classes.html#cliff.command.Command.run) takes [`argparse.Namespace`](https://docs.python.org/2/library/argparse.html#the-namespace-object), so we'd have to convert between those again, and ugh...

Instead, I now propose just using [Docopts](https://github.com/docopt/docopt). It's trivial to implement multi-level commands with Docopts, and I find the concept lovely!

``` python
import sys
from docopt import docopt

def root(argv):
    print('')
    print("test.py")
    print("  raw arguments:")
    print(argv)

    arguments = docopt("""
        Usage:
          test.py <command> [<arguments>...]
    """, argv=argv)
    print("  parsed:")
    print(arguments)

    if arguments['<command>'] == 'first-a':
        firstA(arguments['<arguments>'])
    elif arguments['<command>'] == 'first-b':
        firstB(arguments['<arguments>'])


def firstA(argv):
    print('')
    print("test.py first-a")
    print("  raw arguments:")
    print(argv)

    arguments = docopt("""
        Usage:
          first-a <command> <arguments>
    """, argv=argv)
    print("  parsed:")
    print(arguments)


def firstB(argv):
    print('')
    print("test.py first-b")
    print("  raw arguments:")
    print(argv)

    arguments = docopt("""
        Usage:
          first-b <command> <arguments>
    """, argv=argv)
    print("  parsed:")
    print(arguments)

    if arguments['<command>'] == 'second-b':
        secondB(arguments['<arguments>'])


def secondB(argv):
    print('')
    print("test.py first-b second-b")
    print("  raw arguments:")
    print(argv)

    arguments = docopt("""
        Usage:
          first-b <name>
    """, argv=argv)
    print("  parsed:")
    print(arguments)

    print("Hullo "+arguments['<name>']+"!")


if __name__ == '__main__':
    root(sys.argv[1:])
```

**Comment by 5310** [comment]
Pretty much the only thing we miss would be the free automatic `help` command and interactive mode. We can implement the former ourselves.

**Comment by 5310** [comment]
I only just noticed that Docopts already has a neat example case of a multi-level interface: [docopt/examples/git](https://github.com/docopt/docopt/tree/master/examples/git)

I guess I didn't need to figure that out myself after all... :grin:

...Or, for that matter, slice out the overflow arguments into lower level ones.

**Comment by Hashfyre** [comment]
This is excellent news. I'll be on it.

**Comment by 5310** [comment]
I'm pushing up an updated scaffolding to `dev-scio`.

**Comment by 5310** [comment]
@Hashfyre I had mistakenly added the roadmap label to this issue before. This isn't really a roadmap issue. That label is to contain all our milestone checklists.
